version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcc_backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: gerenciadorExt
      DB_USERNAME: cesara
      DB_PASSWORD: cesara

  nginx:
      image: nginx:stable-alpine
      container_name: tcc_frontend
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./frontend-dist:/usr/share/nginx/html:ro
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - app

  mysql:
    image: mysql:8.0
    container_name: tcc_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: gerenciadorExt
      MYSQL_USER: cesara
      MYSQL_PASSWORD: cesara
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
